### ISSUE TITLE
Serverless Error: Provider "openfaas" is not supported

### ISSUE THREAD

**Issue by prabkumar** [alexellis/serverless-faas#18]
When following the steps in the readme, starting from cloning the repo to running ./test-plugin.sh, the end outcome is that Serverless Error is printed in the console. I am attaching a screenshot to the post.

## Expected Behaviour
./test-plugin.sh should execute without errors

## Current Behaviour

Serverless Error ---------------------------------------
 
     Provider "openfaas" is not supported. Valid values for
     provider are: aws, azure, google, openwhisk. Please
     provide one of those values to the "provider" property
     in serverless.yml.

## Steps to Reproduce (for bugs)

1. $ git clone https://github.com/openfaas/serverless-openfaas
2. $ ./prep.sh
3. $ ./test-plugin.sh

## Your Environment

* Serverless version: 1.11.0

* faas-cli 
       * version: 0.8.3
       * commit: a141dedf94ffeed84412365fd591bdc8999c5a1b

* Docker version `docker version` (e.g. Docker 17.0.05 ): Docker 
[console-log.txt](https://github.com/openfaas-incubator/serverless-openfaas/files/3114782/console-log.txt)
18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS 10.14

[console-log.txt](https://github.com/openfaas-incubator/serverless-openfaas/files/3114784/console-log.txt)

**Comment by rgee0** [comment]
Thanks for your interest.  Please review the status section of the [README](https://github.com/openfaas-incubator/serverless-openfaas#status).

**Comment by alexellis** [comment]
You may be able to change "openfaas" to "faas" in your YAML file.

**Comment by engmsaleh** [comment]
@alexellis I have add `faas` as the provider, but I still get the same error
>   The specified provider "faas" does not exist. 

Here is my serverless yaml file 

```
service: hello-world

provider:
  name: faas
  runtime: python3.6
  memorySize: 128
  timeout: 30
  namespace: lambda

plugins:
  - serverless-openfaas

  
functions:
  hello:
    handler: handler.hello
    namespace: lambda
```
